export const siteMetadata = {
    title: "Type Free - JSON to TypeScript Interface Generator",
    author: 'user01101111000',
    headerTitle: 'Type Free',
    description: "This website is a tool to convert JSON data to TypeScript interface. User friendly and beautiful interface.",
    language: 'en-us',
    theme: 'system',
    siteUrl: 'https://typefree.vercel.app/',
    siteLogo: '/logos/logo.webp',
    socialBanner: '/logos/logo.webp',
    email: 'e88nur@gmail.com',
    github: 'https://github.com/typefree',
    linkedin: 'https://www.linkedin.com/in/elnurguliyev/',
    twitter: 'https://twitter.com/',
    facebook: 'https://facebook.com',
    youtube: 'https://youtube.com/',
    dribbble: 'https://www.dribbble.com',
    locale: 'en-US',
}